**Mini Project**

In [ ]:
# Reading & loading the data

In [78]:
data_file = 'makeSenseOfCensus.csv'
import numpy as np

In [79]:
data = np.genfromtxt(data_file, delimiter=",", skip_header=1,dtype=int)
print("\nData: \n\n", data)


Data: 

 [[39 13  4 ...  0 40  0]
 [50 13  4 ...  0 13  0]
 [38  9  4 ...  0 40  0]
 ...
 [48 13  4 ...  0 58  1]
 [40 10  4 ...  0 40  0]
 [39 13  4 ...  0 50  1]]


In [ ]:
# data shape

In [80]:
data.shape

(1000, 8)

In [81]:
# Printing the type of data

In [82]:
print("\nType of data: \n\n", type(data))


Type of data: 

 <class 'numpy.ndarray'>


In [83]:
#  Step 2: Append the Data

In [84]:
new_records=[[50, 9, 4, 1, 0, 0, 40, 0]]

In [85]:
data_new=np.concatenate([data,new_records])

In [86]:
data_new

array([[39, 13,  4, ...,  0, 40,  0],
       [50, 13,  4, ...,  0, 13,  0],
       [38,  9,  4, ...,  0, 40,  0],
       ...,
       [40, 10,  4, ...,  0, 40,  0],
       [39, 13,  4, ...,  0, 50,  1],
       [50,  9,  4, ...,  0, 40,  0]])

In [87]:
# Step 3: Check if it's a young country or old country

In [88]:
age = data_new[ : ,0]
age

array([39, 50, 38, ..., 40, 39, 50])

In [89]:
max_age=age.max()
print(max_age)

90


**Thus the maximum age is 90**

In [90]:
min_age=np.min(age)
print(min_age)

17


**The minimum age is 17**

In [91]:
age_mean=age.mean()

In [92]:
print(age_mean)

38.06293706293706


In [93]:
round(age_mean,1)

38.1

In [ ]:
#The mean of age is 38.1

In [141]:
age_std=np.std(age)
print(age_std)

13.341478176165857


In [188]:
round(age_std,2)

13.34

In [ ]:
# The standard deviation of the age is 13.34

**Step 4: Checking country's race distribution to identify minorities**

In [142]:
race_0=data_new[data_new[ : ,2]==0]

In [143]:
race_0

array([[34,  4,  0,  1,  0,  0, 45,  0],
       [35, 10,  0,  0,  0,  0, 40,  0],
       [60,  6,  0,  0,  0,  0, 10,  0],
       [51,  9,  0,  1,  0,  0, 40,  0],
       [25, 10,  0,  0,  0,  0, 20,  0],
       [20,  9,  0,  1,  0,  0, 48,  0],
       [23, 10,  0,  0,  0,  0, 25,  0],
       [29,  9,  0,  1,  0,  0, 40,  0],
       [27, 12,  0,  1,  0,  0, 40,  0],
       [31, 12,  0,  0,  0,  0, 40,  0]])

In [144]:
race_1=data_new[data_new[ : ,2]==1]

In [145]:
race_1


array([[  30,   13,    1,    1,    0,    0,   40,    1],
       [  40,   11,    1,    1,    0,    0,   40,    1],
       [  54,   10,    1,    1,    0,    0,   60,    1],
       [  30,    9,    1,    0,    0, 1573,   35,    0],
       [  49,   10,    1,    1,    0,    0,   40,    1],
       [  33,   13,    1,    0,    0,    0,   40,    0],
       [  44,   14,    1,    0,    0,    0,   40,    0],
       [  28,    9,    1,    0,    0,    0,   40,    0],
       [  60,    9,    1,    1,    0,    0,   40,    0],
       [  42,    9,    1,    1,    0,    0,   40,    1],
       [  37,   10,    1,    1,    0,    0,   75,    1],
       [  39,   14,    1,    0, 3464,    0,   40,    0],
       [  21,   10,    1,    0,    0,    0,   25,    0],
       [  24,   10,    1,    0,    0,    0,   40,    0],
       [  34,   14,    1,    1, 7298,    0,   35,    1],
       [  27,   10,    1,    1,    0, 1980,   40,    0],
       [  40,   11,    1,    1,    0,    0,   40,    1],
       [  55,    9,    1,    0,

In [146]:
race_2=data_new[data_new[: ,2]==2]

In [147]:
race_2

array([[  53,    7,    2,    1,    0,    0,   40,    0],
       [  28,   13,    2,    0,    0,    0,   40,    0],
       [  49,    5,    2,    0,    0,    0,   16,    0],
       [  37,   10,    2,    1,    0,    0,   80,    1],
       [  32,   12,    2,    1,    0,    0,   50,    0],
       [  54,    9,    2,    0,    0,    0,   20,    0],
       [  35,    5,    2,    1,    0,    0,   40,    0],
       [  20,   10,    2,    1,    0,    0,   44,    0],
       [  22,   10,    2,    1,    0,    0,   15,    0],
       [  57,   13,    2,    1,    0,    0,   40,    1],
       [  31,   13,    2,    0,    0,    0,   40,    0],
       [  28,   10,    2,    0,    0,    0,   25,    0],
       [  32,    9,    2,    1,    0,    0,   40,    0],
       [  49,   11,    2,    1,    0,    0,   40,    1],
       [  30,   13,    2,    1,    0,    0,   40,    0],
       [  19,   10,    2,    1,    0,    0,   35,    0],
       [  46,   12,    2,    0,    0,    0,   36,    0],
       [  31,    9,    2,    0,

In [148]:
race_3=data_new[data_new[: ,2]==3]

In [149]:
race_3

array([[  25,   10,    3,    0,    0,    0,   40,    0],
       [  33,   10,    3,    0,    0,    0,   40,    0],
       [  65,    7,    3,    1,    0,    0,   40,    0],
       [  28,    4,    3,    1,    0, 2179,   40,    0],
       [  44,    7,    3,    0,    0,    0,   46,    0],
       [  40,   13,    3,    0,    0,    0,   55,    1]])

In [150]:
race_4=data_new[data_new[: ,2]==4]

In [151]:
race_4

array([[39, 13,  4, ...,  0, 40,  0],
       [50, 13,  4, ...,  0, 13,  0],
       [38,  9,  4, ...,  0, 40,  0],
       ...,
       [40, 10,  4, ...,  0, 40,  0],
       [39, 13,  4, ...,  0, 50,  1],
       [50,  9,  4, ...,  0, 40,  0]])

In [ ]:
# Determining the length of the race distribution respectively

In [152]:
len_0=len(race_0)

In [153]:
len_0

10

In [154]:
len_1=len(race_1)

In [155]:
len_1

27

In [156]:
len_2=len(race_2)

In [157]:
len_2

110

In [158]:
len_3=len(race_3)

In [159]:
len_3

6

In [160]:
len_4=len(race_4)

In [161]:
len_4

848

In [ ]:
# As seen from the length of race distributions, race with minimum number of citizens is race_3 with 6 citizens

In [162]:
race_min_citizens=len_3

In [163]:
race_min_citizens

6

In [164]:
minority_race=len_3

In [165]:
minority_race

6

In [166]:
# Step 5: Checking if gov't policy is in place

In [167]:
senior_citizens=data_new[age>60]

In [168]:
senior_citizens

array([[   79,    10,     4,     1,     0,     0,    20,     0],
       [   67,     6,     4,     1,     0,     0,     2,     0],
       [   76,    14,     4,     1,     0,     0,    40,     1],
       [   61,     9,     4,     1,     0,     0,    40,     0],
       [   70,    10,     4,     1,     0,     0,    40,     0],
       [   64,     7,     4,     1,     0,  2179,    40,     0],
       [   71,    10,     2,     1,     0,  1816,     2,     0],
       [   68,     2,     4,     0,     0,     0,    20,     0],
       [   66,    11,     4,     0,     0,     0,    20,     0],
       [   64,     2,     4,     1,     0,     0,    40,     0],
       [   90,     9,     2,     1,     0,  2206,    40,     0],
       [   66,     9,     4,     1,  1409,     0,    50,     0],
       [   75,    11,     4,     0,     0,     0,    20,     0],
       [   65,     9,     4,     0,     0,     0,    40,     0],
       [   64,     9,     4,     1,     0,     0,    40,     1],
       [   61,     9,    

In [169]:
senior_citizens_len=len(senior_citizens)

In [170]:
senior_citizens_len

61

In [171]:
working_hours_sum=sum(senior_citizens[:,6])

In [172]:
working_hours_sum

1917

In [173]:
avg_working_hours=working_hours_sum/senior_citizens_len

**bold text**

In [174]:
avg_working_hours

31.42622950819672

**As the average woking hours>25, so policy is not in place**

In [175]:
# Step 6: Checking that higher educated people have better pay in general.

In [176]:
data_file = 'makeSenseOfCensus.csv'

In [177]:
high = data_new[data_new[: ,1]>10]

In [178]:
high

array([[39, 13,  4, ...,  0, 40,  0],
       [50, 13,  4, ...,  0, 13,  0],
       [28, 13,  2, ...,  0, 40,  0],
       ...,
       [45, 14,  4, ...,  0, 45,  0],
       [48, 13,  4, ...,  0, 58,  1],
       [39, 13,  4, ...,  0, 50,  1]])

In [179]:
low = data_new[data_new[: ,1]<=10]

In [180]:
low

array([[38,  9,  4, ...,  0, 40,  0],
       [53,  7,  2, ...,  0, 40,  0],
       [49,  5,  2, ...,  0, 16,  0],
       ...,
       [56,  9,  4, ...,  0, 55,  1],
       [40, 10,  4, ...,  0, 40,  0],
       [50,  9,  4, ...,  0, 40,  0]])

In [181]:
avg_pay_high=high[:,7]
avg_pay_high_mean=avg_pay_high.mean()

In [182]:
avg_pay_high_mean

0.42813455657492355

In [183]:
print(round(avg_pay_high_mean,2))

0.43


In [184]:
avg_pay_low=low[:,7]


In [185]:
avg_pay_low_mean=avg_pay_low.mean()

In [186]:
avg_pay_low_mean

0.13649851632047477

In [187]:
round(avg_pay_low_mean,2)

0.14